# Generated by Django 6.0.2 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('faculty', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='facultyprofile',
			name='profile_photo',
			field=models.ImageField(blank=True, null=True, upload_to='faculty/profile_photos/'),
		),
	]