# Generated by Django 6.0.2 on 2026-04-03 04:28

import apps.faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.faculty.models.faculty_profile_photo_upload_to),
        ),
    ]
