# Generated by Django 6.0.2 on 2026-03-18 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('roll_no', models.PositiveIntegerField(unique=True)),
                ('course', models.CharField(choices=[('DCST', 'DCST'), ('DME', 'DME'), ('DCE', 'DCE'), ('DSE', 'DSE'), ('DCFS', 'DCFS'), ('DETC', 'DETC'), ('DEE', 'DEE')], max_length=10)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_contact', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
