# Generated by Django 6.0.2 on 2026-04-03 04:28

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.student_profile_photo_upload_to),
        ),
    ]
