# Generated by Django 6.0.2 on 2026-04-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('Event', 'Event'), ('Holiday', 'Holiday'), ('Exam', 'Exam'), ('Notice', 'Notice')], default='Event', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date', 'title'],
            },
        ),
    ]
