# Generated by Django 6.0.2 on 2026-04-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_facultyprofile_profile_photo'),
        ('students', '0005_academiccalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='advisor_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to='faculty.facultyprofile'),
        ),
    ]
