# Generated by Django 6.0.2 on 2026-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_feestructure_studentfeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='overall_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
